# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-26 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='users',
            field=models.ManyToManyField(related_name='jobs', to='exam.User'),
        ),
    ]
