# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-26 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20190226_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='users',
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='exam.User'),
            preserve_default=False,
        ),
    ]
