# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-26 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20190226_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Description',
            field=models.CharField(default='null', max_length=45),
            preserve_default=False,
        ),
    ]
